// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectClient(arg1) {
  return window['go']['main']['App']['ConnectClient'](arg1);
}

export function ConnectHost(arg1) {
  return window['go']['main']['App']['ConnectHost'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DisconnectClient(arg1) {
  return window['go']['main']['App']['DisconnectClient'](arg1);
}

export function DisconnectHost(arg1) {
  return window['go']['main']['App']['DisconnectHost'](arg1);
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function Publish(arg1) {
  return window['go']['main']['App']['Publish'](arg1);
}

export function Subscribe(arg1) {
  return window['go']['main']['App']['Subscribe'](arg1);
}

export function Unsubscribe(arg1, arg2) {
  return window['go']['main']['App']['Unsubscribe'](arg1, arg2);
}
