// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.ConnectionConfig):Promise<void>;

export function ConnectClient(arg1:main.ConnectionConfig):Promise<void>;

export function ConnectHost(arg1:main.ConnectionConfig):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DisconnectClient(arg1:string):Promise<void>;

export function DisconnectHost(arg1:string):Promise<void>;

export function GetMessages():Promise<Array<main.MessageItem>>;

export function Publish(arg1:main.PublishConfig):Promise<void>;

export function Subscribe(arg1:main.SubscribeConfig):Promise<void>;

export function Unsubscribe(arg1:string,arg2:string):Promise<void>;
