// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1:string,arg2:string,arg3:number):Promise<string>;

export function DeleteUser(arg1:number):Promise<string>;

export function GetAllUsers():Promise<Array<{[key: string]: any}>>;

export function GetUser(arg1:number):Promise<{[key: string]: any}>;

export function Greet(arg1:string):Promise<string>;

export function SearchUsers(arg1:string,arg2:number,arg3:number):Promise<{[key: string]: any}>;

export function UpdateUser(arg1:number,arg2:string,arg3:string,arg4:number):Promise<string>;
