// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchUsers(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchUsers'](arg1, arg2, arg3);
}

export function UpdateUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2, arg3, arg4);
}
